Watching for file changes with StatReloader
[26/Mar/2022 17:05:28] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 17:05:28] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:30] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 17:05:30] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 17:05:30] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /admin/ HTTP/1.1" 200 3350
[26/Mar/2022 17:05:34] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[26/Mar/2022 17:05:34] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[26/Mar/2022 17:05:36] "GET /admin/logout/ HTTP/1.1" 200 1532
[26/Mar/2022 17:05:37] "GET /admin/ HTTP/1.1" 302 0
[26/Mar/2022 17:05:37] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2235
[26/Mar/2022 17:05:37] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[26/Mar/2022 17:05:41] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[26/Mar/2022 17:05:41] "GET /admin/ HTTP/1.1" 200 3350
[26/Mar/2022 17:05:44] "GET /admin/auth/user/ HTTP/1.1" 200 8167
[26/Mar/2022 17:05:44] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6932
[26/Mar/2022 17:05:44] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[26/Mar/2022 17:05:44] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[26/Mar/2022 17:05:44] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[26/Mar/2022 17:05:44] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[26/Mar/2022 17:05:44] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[26/Mar/2022 17:05:44] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[26/Mar/2022 17:05:44] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[26/Mar/2022 17:05:44] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[26/Mar/2022 17:05:44] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[26/Mar/2022 17:05:44] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[26/Mar/2022 17:05:44] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[26/Mar/2022 17:05:44] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[26/Mar/2022 17:05:44] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[26/Mar/2022 17:05:47] "GET /admin/auth/user/add/ HTTP/1.1" 200 7203
[26/Mar/2022 17:05:47] "GET /static/admin/css/forms.css HTTP/1.1" 200 8878
[26/Mar/2022 17:05:47] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[26/Mar/2022 17:05:47] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[26/Mar/2022 17:05:47] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[26/Mar/2022 17:05:47] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[26/Mar/2022 17:05:57] "POST /admin/auth/user/add/ HTTP/1.1" 200 7395
[26/Mar/2022 17:05:57] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[26/Mar/2022 17:06:11] "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[26/Mar/2022 17:06:11] "GET /admin/auth/user/2/change/ HTTP/1.1" 200 15688
[26/Mar/2022 17:06:11] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
[26/Mar/2022 17:06:11] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
[26/Mar/2022 17:06:11] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
[26/Mar/2022 17:06:11] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[26/Mar/2022 17:06:11] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[26/Mar/2022 17:06:11] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[26/Mar/2022 17:06:11] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[26/Mar/2022 17:06:11] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[26/Mar/2022 17:06:11] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[26/Mar/2022 17:06:11] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
Watching for file changes with StatReloader
[26/Mar/2022 19:56:48] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 19:56:48] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Mar/2022 19:56:48] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[26/Mar/2022 19:56:48] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[26/Mar/2022 19:56:48] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[26/Mar/2022 20:04:32] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:04:32] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 20:04:32] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:04:32] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:04:32] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:04:40] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:04:44] "GET /admin/ HTTP/1.1" 200 3653
[26/Mar/2022 20:04:44] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[26/Mar/2022 20:04:44] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
[26/Mar/2022 20:04:44] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[26/Mar/2022 20:04:44] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
[26/Mar/2022 20:04:44] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
[26/Mar/2022 20:04:44] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[26/Mar/2022 20:04:44] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[26/Mar/2022 20:10:13] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:10:13] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 20:10:13] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:10:13] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:10:13] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 107, in check_url_settings
    value = getattr(settings, name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 93, in __getattr__
    val = self._add_script_prefix(val)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 140, in _add_script_prefix
    if value.startswith(("http://", "https://", "/")):
AttributeError: 'PosixPath' object has no attribute 'startswith'
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 107, in check_url_settings
    value = getattr(settings, name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 93, in __getattr__
    val = self._add_script_prefix(val)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 140, in _add_script_prefix
    if value.startswith(("http://", "https://", "/")):
AttributeError: 'PosixPath' object has no attribute 'startswith'
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
[26/Mar/2022 20:31:33] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:31:33] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Mar/2022 20:31:33] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[26/Mar/2022 20:31:33] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[26/Mar/2022 20:31:33] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Mar/2022 20:32:02] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:32:02] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
Watching for file changes with StatReloader
[26/Mar/2022 20:34:46] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:34:46] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 20:34:46] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:34:46] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:34:46] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:34:52] "GET /admin/ HTTP/1.1" 200 3653
[26/Mar/2022 20:34:52] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[26/Mar/2022 20:34:52] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[26/Mar/2022 20:34:52] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
[26/Mar/2022 20:34:52] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
[26/Mar/2022 20:34:52] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
[26/Mar/2022 20:34:52] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[26/Mar/2022 20:34:52] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[26/Mar/2022 20:34:56] "GET / HTTP/1.1" 200 10773
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 107, in check_url_settings
    value = getattr(settings, name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 93, in __getattr__
    val = self._add_script_prefix(val)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 140, in _add_script_prefix
    if value.startswith(("http://", "https://", "/")):
AttributeError: 'PosixPath' object has no attribute 'startswith'
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
[26/Mar/2022 20:36:34] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:36:34] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 20:36:34] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:36:34] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 20:36:34] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
Invalid HTTP_HOST header: '172.30.1.46:8000'. You may need to add '172.30.1.46' to ALLOWED_HOSTS.
Bad Request: /
[26/Mar/2022 20:57:36] "GET / HTTP/1.1" 400 58958
Invalid HTTP_HOST header: '172.30.1.46:8000'. You may need to add '172.30.1.46' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[26/Mar/2022 20:57:36] "GET /favicon.ico HTTP/1.1" 400 59013
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
[26/Mar/2022 20:58:08] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 20:58:08] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Mar/2022 20:58:08] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[26/Mar/2022 20:58:08] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Mar/2022 20:58:08] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
Not Found: /favicon.ico
[26/Mar/2022 20:58:08] "GET /favicon.ico HTTP/1.1" 404 2110
[26/Mar/2022 21:17:20] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 21:17:20] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 21:17:20] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:17:20] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:17:20] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:20:04] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 21:20:14] "GET / HTTP/1.1" 200 10773
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Bad Request: /
[26/Mar/2022 21:20:18] "GET / HTTP/1.1" 400 60882
[26/Mar/2022 21:22:09] "GET / HTTP/1.1" 200 10773
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[26/Mar/2022 21:31:11] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 21:31:11] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Mar/2022 21:31:11] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Mar/2022 21:31:11] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[26/Mar/2022 21:31:11] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[26/Mar/2022 21:41:50] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 21:41:50] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 21:41:50] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:41:50] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:41:50] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:57:58] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 21:57:58] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 21:57:58] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:57:58] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 21:57:58] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 22:12:53] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 22:12:53] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 22:12:54] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 22:12:54] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 22:12:54] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is starting up


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 576, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is starting up

/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[26/Mar/2022 22:46:53] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 22:46:53] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[26/Mar/2022 22:46:53] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[26/Mar/2022 22:46:53] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[26/Mar/2022 22:46:53] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
Not Found: /favicon.ico
[26/Mar/2022 22:46:53] "GET /favicon.ico HTTP/1.1" 404 2108
[26/Mar/2022 22:47:00] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 23:11:51] "GET / HTTP/1.1" 200 10773
[26/Mar/2022 23:11:51] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[26/Mar/2022 23:11:51] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 23:11:51] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[26/Mar/2022 23:11:51] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[28/Mar/2022 00:29:03] "GET / HTTP/1.1" 200 10773
[28/Mar/2022 00:29:03] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[28/Mar/2022 00:29:03] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[28/Mar/2022 00:29:03] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[28/Mar/2022 00:29:03] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  the database system is starting up


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 576, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  the database system is starting up

Watching for file changes with StatReloader
[29/Mar/2022 01:15:54] "GET / HTTP/1.1" 200 10773
[29/Mar/2022 01:15:54] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[29/Mar/2022 01:15:54] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[29/Mar/2022 01:15:54] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[29/Mar/2022 01:15:54] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
Not Found: /favicon.ico
[29/Mar/2022 01:15:54] "GET /favicon.ico HTTP/1.1" 404 2108
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[29/Mar/2022 03:50:48] "GET / HTTP/1.1" 200 10773
[29/Mar/2022 03:51:02] "GET / HTTP/1.1" 200 10773
[29/Mar/2022 03:51:05] "GET /admin HTTP/1.1" 301 0
[29/Mar/2022 03:51:05] "GET /admin/ HTTP/1.1" 200 3653
[29/Mar/2022 03:51:05] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
[29/Mar/2022 03:51:05] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[29/Mar/2022 03:51:05] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
[29/Mar/2022 03:51:05] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[29/Mar/2022 03:51:05] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
[29/Mar/2022 03:51:05] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[29/Mar/2022 03:51:05] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[29/Mar/2022 03:51:14] "GET / HTTP/1.1" 200 10773
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[30/Mar/2022 23:23:42] "GET / HTTP/1.1" 200 10773
[30/Mar/2022 23:23:42] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[30/Mar/2022 23:23:44] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[30/Mar/2022 23:23:44] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[30/Mar/2022 23:23:44] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
[30/Mar/2022 23:23:44] "GET /favicon.ico HTTP/1.1" 404 2108
[30/Mar/2022 23:24:02] "GET /admin/ HTTP/1.1" 200 3653
[30/Mar/2022 23:24:02] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[30/Mar/2022 23:24:02] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
[30/Mar/2022 23:24:02] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
[30/Mar/2022 23:24:02] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[30/Mar/2022 23:24:02] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[30/Mar/2022 23:24:02] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
[30/Mar/2022 23:24:02] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[30/Mar/2022 23:24:02] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:24:02] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:24:02] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:24:02] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
/app/newb/urls.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 22, in <module>
    router.register(r'users', views.UserViewSet)
AttributeError: module 'newb.quickstart.views' has no attribute 'UserViewSet'
/app/newb/quickstart/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 23, in <module>
    router.register(r'groups', vies.GroupViewSet)
NameError: name 'vies' is not defined
/app/newb/urls.py changed, reloading.
Watching for file changes with StatReloader
[30/Mar/2022 23:37:58] "GET /admin/ HTTP/1.1" 200 3653
[30/Mar/2022 23:37:58] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:37:58] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[30/Mar/2022 23:38:01] "GET / HTTP/1.1" 200 10499
[30/Mar/2022 23:38:01] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[30/Mar/2022 23:38:01] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[30/Mar/2022 23:38:01] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[30/Mar/2022 23:38:01] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[30/Mar/2022 23:38:01] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[30/Mar/2022 23:38:01] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
/app/newb/quickstart/serializers.py changed, reloading.
Watching for file changes with StatReloader
Forbidden: /users/
[30/Mar/2022 23:52:46] "GET /users/ HTTP/1.1" 403 96
Forbidden: /users/1/
[30/Mar/2022 23:53:10] "GET /users/1/ HTTP/1.1" 403 96
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snippets'
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 245, in create
    app_module = import_module(app_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snippets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 247, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'snippets'. Check that 'newb.snippets.apps.SnippetsConfig.name' is correct.
/app/newb/settings.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snippets'
Watching for file changes with StatReloader
[31/Mar/2022 00:10:31] "GET /admin/ HTTP/1.1" 200 3653
[31/Mar/2022 00:10:31] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:10:31] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:10:32] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:10:32] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:10:32] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET / HTTP/1.1" 200 10499
[31/Mar/2022 00:10:36] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[31/Mar/2022 00:10:36] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[31/Mar/2022 00:10:46] "GET /snippets/ HTTP/1.1" 200 12079
[31/Mar/2022 00:11:10] "GET /admin/ HTTP/1.1" 200 3653
[31/Mar/2022 00:11:12] "GET /admin/ HTTP/1.1" 200 3653
/app/snippets/admin.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/snippets/admin.py", line 5, in <module>
    class SnippetAdmin(admin.ModelAdmin):
TypeError: 'NoneType' object is not callable
/app/snippets/admin.py changed, reloading.
Watching for file changes with StatReloader
[31/Mar/2022 00:16:45] "GET /admin/ HTTP/1.1" 200 4326
[31/Mar/2022 00:16:45] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:16:45] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:16:46] "GET /admin/snippets/snippet/ HTTP/1.1" 200 5122
[31/Mar/2022 00:16:46] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6932
[31/Mar/2022 00:16:46] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[31/Mar/2022 00:16:46] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[31/Mar/2022 00:16:46] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[31/Mar/2022 00:16:46] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[31/Mar/2022 00:16:46] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[31/Mar/2022 00:16:46] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[31/Mar/2022 00:16:46] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[31/Mar/2022 00:16:46] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[31/Mar/2022 00:16:46] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:16:46] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
Internal Server Error: /admin/snippets/snippet/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 804, in get_form
    return modelform_factory(self.model, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 648, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 306, in __new__
    fields = fields_for_model(
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 197, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'created' cannot be specified for Snippet model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1885, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1745, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1781, in _changeform_view
    ModelForm = self.get_form(
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 806, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'created' cannot be specified for Snippet model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class SnippetAdmin.
[31/Mar/2022 00:16:48] "GET /admin/snippets/snippet/add/ HTTP/1.1" 500 128655
/app/snippets/admin.py changed, reloading.
Watching for file changes with StatReloader
[31/Mar/2022 00:17:09] "GET /admin/snippets/snippet/ HTTP/1.1" 200 5122
[31/Mar/2022 00:17:10] "GET /admin/snippets/snippet/ HTTP/1.1" 200 5122
[31/Mar/2022 00:17:10] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:17:12] "GET /admin/snippets/snippet/ HTTP/1.1" 200 5122
[31/Mar/2022 00:17:12] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:17:13] "GET /admin/snippets/snippet/add/ HTTP/1.1" 200 32690
[31/Mar/2022 00:17:13] "GET /static/admin/css/forms.css HTTP/1.1" 200 8878
[31/Mar/2022 00:17:13] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[31/Mar/2022 00:17:13] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:17:13] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[31/Mar/2022 00:17:13] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[31/Mar/2022 00:18:56] "POST /admin/snippets/snippet/add/ HTTP/1.1" 302 0
[31/Mar/2022 00:18:56] "GET /admin/snippets/snippet/ HTTP/1.1" 200 6578
[31/Mar/2022 00:18:56] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:18:56] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[31/Mar/2022 00:18:57] "GET /admin/snippets/snippet/1/change/ HTTP/1.1" 200 33024
[31/Mar/2022 00:18:57] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:19:00] "GET /admin/snippets/snippet/ HTTP/1.1" 200 6354
[31/Mar/2022 00:19:03] "GET /admin/snippets/snippet/add/ HTTP/1.1" 200 32690
[31/Mar/2022 00:19:03] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:21:12] "POST /admin/snippets/snippet/add/ HTTP/1.1" 302 0
[31/Mar/2022 00:21:12] "GET /admin/snippets/snippet/ HTTP/1.1" 200 6800
[31/Mar/2022 00:21:12] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:22:23] "GET /admin/snippets/snippet/1/change/ HTTP/1.1" 200 33024
[31/Mar/2022 00:22:23] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:22:23] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:22:23] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:22:25] "GET /admin/snippets/snippet/ HTTP/1.1" 200 6576
[31/Mar/2022 00:22:26] "GET /admin/snippets/snippet/2/change/ HTTP/1.1" 200 33089
[31/Mar/2022 00:22:26] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:28:31] "POST /admin/snippets/snippet/2/change/ HTTP/1.1" 302 0
[31/Mar/2022 00:28:31] "GET /admin/snippets/snippet/ HTTP/1.1" 200 6800
[31/Mar/2022 00:28:31] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[31/Mar/2022 00:28:31] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:28:31] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /snippets HTTP/1.1" 301 0
[31/Mar/2022 00:29:20] "GET /snippets/ HTTP/1.1" 200 12827
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[31/Mar/2022 00:29:20] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[31/Mar/2022 00:29:24] "GET /snippets/2 HTTP/1.1" 200 13766
[31/Mar/2022 00:29:34] "OPTIONS /snippets/2 HTTP/1.1" 200 13758
[31/Mar/2022 00:29:36] "GET /snippets/2 HTTP/1.1" 200 13766
[31/Mar/2022 00:29:38] "GET /snippets/2?format=json HTTP/1.1" 200 257
[31/Mar/2022 00:29:42] "GET /snippets/2?format=api HTTP/1.1" 200 13854
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 29, in <module>
    path('', include('snippets.urls')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/snippets/urls.py", line 6, in <module>
    path('snippets/', views.snippet_list),
AttributeError: module 'snippets.views' has no attribute 'snippet_list'
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 29, in <module>
    path('', include('snippets.urls')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/snippets/urls.py", line 3, in <module>
    from snippets import views
  File "/app/snippets/views.py", line 64
    except: Snippet.DoesNotExist:
                                ^
SyntaxError: invalid syntax
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 29, in <module>
    path('', include('snippets.urls')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/snippets/urls.py", line 6, in <module>
    path('snippets/', views.snippet_list),
AttributeError: module 'snippets.views' has no attribute 'snippet_list'
/app/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/newb/urls.py", line 29, in <module>
    path('', include('snippets.urls')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/snippets/urls.py", line 3, in <module>
    from snippets import views
  File "/app/snippets/views.py", line 125
    class SnippetDetailGB(generics.RetrieveUpdateDestroyAPIView)
                                                               ^
SyntaxError: invalid syntax
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /snippets/
[31/Mar/2022 01:55:53] "GET /snippets/ HTTP/1.1" 404 6395
[31/Mar/2022 01:55:57] "GET /snippets/api HTTP/1.1" 301 0
[31/Mar/2022 01:55:57] "GET /snippets/api/ HTTP/1.1" 200 12849
[31/Mar/2022 01:55:57] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[31/Mar/2022 01:55:57] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /snippets/api/2/
[31/Mar/2022 01:56:06] "GET /snippets/api/2/ HTTP/1.1" 404 6413
[31/Mar/2022 01:56:09] "GET /snippets/api/2 HTTP/1.1" 200 13814
[31/Mar/2022 01:56:18] "GET /snippets/mixin HTTP/1.1" 301 0
[31/Mar/2022 01:56:18] "GET /snippets/mixin/ HTTP/1.1" 200 63005
[31/Mar/2022 01:56:33] "GET /snippets/generic/ HTTP/1.1" 200 63023
[31/Mar/2022 01:56:58] "GET /snippets/mixin/ HTTP/1.1" 200 63005
[31/Mar/2022 01:57:00] "GET /snippets/mixin/2 HTTP/1.1" 200 64201
[31/Mar/2022 01:57:09] "GET /snippets/generic/1 HTTP/1.1" 200 63999
/app/snippets/views.py changed, reloading.
Watching for file changes with StatReloader
/app/snippets/urls.py changed, reloading.
Watching for file changes with StatReloader
[31/Mar/2022 01:58:50] "GET /snippets/generic/1 HTTP/1.1" 200 64105
[31/Mar/2022 01:58:53] "GET /snippets/ HTTP/1.1" 200 12779
[31/Mar/2022 01:59:02] "GET /snippets/?format=json HTTP/1.1" 200 376
[31/Mar/2022 01:59:08] "GET /snippets/generic HTTP/1.1" 301 0
[31/Mar/2022 01:59:08] "GET /snippets/generic/ HTTP/1.1" 200 63129
[31/Mar/2022 01:59:11] "GET /snippets/generic/?format=json HTTP/1.1" 200 376
[31/Mar/2022 01:59:19] "GET /snippets/generic/2 HTTP/1.1" 200 64540
[31/Mar/2022 02:01:22] "PUT /snippets/generic/2 HTTP/1.1" 200 64187
[31/Mar/2022 02:01:38] "GET /snippets/generic/2 HTTP/1.1" 200 64187
[31/Mar/2022 02:01:43] "GET /snippets/generic/2?format=api HTTP/1.1" 200 64297
[31/Mar/2022 02:01:45] "GET /snippets/generic/2?format=json HTTP/1.1" 200 156
[31/Mar/2022 02:01:52] "GET /snippets/generic/ HTTP/1.1" 200 63005
[31/Mar/2022 02:03:24] "POST /snippets/generic/ HTTP/1.1" 201 62707
[31/Mar/2022 02:03:31] "GET /snippets/generic/?format=json HTTP/1.1" 200 391
[31/Mar/2022 02:03:37] "GET / HTTP/1.1" 200 10499
[31/Mar/2022 02:03:40] "GET /snippets/ HTTP/1.1" 200 12951
[31/Mar/2022 02:04:10] "GET /snippets/generic/ HTTP/1.1" 200 63301
[31/Mar/2022 02:04:24] "GET /snippets/ HTTP/1.1" 200 12951
[31/Mar/2022 02:04:27] "OPTIONS /snippets/ HTTP/1.1" 200 12394
[31/Mar/2022 02:04:30] "OPTIONS /snippets/ HTTP/1.1" 200 12394
/app/snippets/models.py changed, reloading.
Watching for file changes with StatReloader
/app/snippets/models.py changed, reloading.
Watching for file changes with StatReloader
/app/snippets/admin.py changed, reloading.
Watching for file changes with StatReloader
